# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongoid_nested_set}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brandon Turner"]
  s.date = %q{2010-12-17}
  s.description = %q{Fully featured tree implementation for Mongoid using the nested set model}
  s.email = %q{bturner@bltweb.net}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/mongoid_nested_set.rb",
    "lib/mongoid_nested_set/base.rb",
    "lib/mongoid_nested_set/document.rb",
    "lib/mongoid_nested_set/fields.rb",
    "lib/mongoid_nested_set/outline_number.rb",
    "lib/mongoid_nested_set/rebuild.rb",
    "lib/mongoid_nested_set/relations.rb",
    "lib/mongoid_nested_set/remove_order_by.rb",
    "lib/mongoid_nested_set/update.rb",
    "lib/mongoid_nested_set/validation.rb",
    "mongoid_nested_set.gemspec",
    "spec/matchers/nestedset_pos.rb",
    "spec/models/circle_node.rb",
    "spec/models/node.rb",
    "spec/models/node_without_nested_set.rb",
    "spec/models/numbering_node.rb",
    "spec/models/renamed_fields.rb",
    "spec/models/shape_node.rb",
    "spec/models/square_node.rb",
    "spec/models/test_document.rb",
    "spec/models/unscoped_node.rb",
    "spec/mongoid_nested_set_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/thinkwell/mongoid_nested_set}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Nested set based tree implementation for Mongoid}
  s.test_files = [
    "spec/matchers/nestedset_pos.rb",
    "spec/models/circle_node.rb",
    "spec/models/node.rb",
    "spec/models/node_without_nested_set.rb",
    "spec/models/numbering_node.rb",
    "spec/models/renamed_fields.rb",
    "spec/models/shape_node.rb",
    "spec/models/square_node.rb",
    "spec/models/test_document.rb",
    "spec/models/unscoped_node.rb",
    "spec/mongoid_nested_set_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, [">= 2.0.0.beta.20"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec-core>, [">= 0"])
    else
      s.add_dependency(%q<mongoid>, [">= 2.0.0.beta.20"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec-core>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid>, [">= 2.0.0.beta.20"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec-core>, [">= 0"])
  end
end

