# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mongoid_nested_set"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brandon Turner"]
  s.date = "2012-07-17"
  s.description = "Fully featured tree implementation for Mongoid using the nested set model"
  s.email = "bturner@bltweb.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/mongoid_nested_set.rb",
    "lib/mongoid_nested_set/base.rb",
    "lib/mongoid_nested_set/document.rb",
    "lib/mongoid_nested_set/fields.rb",
    "lib/mongoid_nested_set/outline_number.rb",
    "lib/mongoid_nested_set/rebuild.rb",
    "lib/mongoid_nested_set/relations.rb",
    "lib/mongoid_nested_set/remove_order_by.rb",
    "lib/mongoid_nested_set/update.rb",
    "lib/mongoid_nested_set/validation.rb",
    "mongoid_nested_set.gemspec",
    "spec/matchers/nestedset_pos.rb",
    "spec/models/circle_node.rb",
    "spec/models/node.rb",
    "spec/models/node_without_nested_set.rb",
    "spec/models/numbering_node.rb",
    "spec/models/renamed_fields.rb",
    "spec/models/shape_node.rb",
    "spec/models/square_node.rb",
    "spec/models/test_document.rb",
    "spec/models/unscoped_node.rb",
    "spec/mongoid_nested_set_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/thinkwell/mongoid_nested_set"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Nested set based tree implementation for Mongoid"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, [">= 3.0.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<simplecov-rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec-core>, ["~> 2.0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<mongoid>, [">= 3.0.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<simplecov-rcov>, [">= 0"])
      s.add_dependency(%q<rspec-core>, ["~> 2.0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid>, [">= 3.0.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<simplecov-rcov>, [">= 0"])
    s.add_dependency(%q<rspec-core>, ["~> 2.0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

